### ISSUE TITLE
FindSDL2 license

### ISSUE THREAD

**Issue by Robert42** [eikel/CMake-FindSDL-Test#1]
Hello,

in the FindSDL2.cmake file, the license tells about an accompying `Copyright.txt` file, which is missing in this repository. [Quote](https://github.com/eikel/CMake-FindSDL-Test/blob/43b1751eda0e7bb851b339b0a009b64957272830/SDLUse/cmake/FindSDL2.cmake#L27-L28):

```
# Distributed under the OSI-approved BSD License (the "License");
# see accompanying file Copyright.txt for details.
```

**Comment by eikel** [comment]
This repository, as the name suggests, was intended to be a test only. It was used as an example.
You can find [CMake's `Copyright.txt` file in its root directory](https://cmake.org/gitweb?p=cmake.git;a=blob;f=Copyright.txt;hb=HEAD).
For SDL version 1, you should consider using [CMake's integrated find module](https://cmake.org/gitweb?p=cmake.git;a=blob;f=Modules/FindSDL.cmake;hb=HEAD).

**Comment by Robert42** [comment]
Thanks :)
